// ═══════════════════════════════════════════════════════════════════
// Facharzt-Examen: Erweiterte Subfragen pro Fall (schwieriger)
// Wird an QUIZ_CASES gehängt als .expert[] Array
// ═══════════════════════════════════════════════════════════════════
//
// Unterschied zu .sub[]:
// - Alle Distraktoren sind plausible Differentialdiagnosen
// - Fragen erfordern exaktes Wissen (Zahlen, Kontraindikationen, Algorithmen)
// - "Welche Aussage ist FALSCH?"-Typ
// - Praxisrelevante Fallstricke
//

const QUIZ_EXPERT = {

// ── Fall 1: Trisomie 21 ──────────────────────────────────────────
1: [
  { q: 'Welche Aussage zur Trisomie 21 ist FALSCH?', choices: ['95% entstehen durch meiotische Non-Disjunction in Meiose I der Mutter', 'Das Wiederholungsrisiko bei freier Trisomie beträgt ca. 25%', 'AVSD ist der charakteristischste Herzfehler', 'Das Risiko steigt exponentiell mit mütterlichem Alter ab 35'], answer: 1, explain: 'FALSCH ist 25%. Das Wiederholungsrisiko bei freier Trisomie 21 beträgt ~1% + altersabhängiges Basisrisiko. 25% wäre autosomal rezessiv.' },
  { q: 'Eine 28-jährige Erstgebärende hat ein auffälliges Ersttrimesterscreening (Risiko 1:150 für Trisomie 21). NIPT bestätigt hohes Risiko. Nächster Schritt?', choices: ['Amniozentese/CVS zur Bestätigung (NIPT ist Screening, nicht diagnostisch!)', 'Diagnose Down-Syndrom mitteilen und Beratung', 'NIPT wiederholen in 4 Wochen', 'Sofort Karyotyp aus mütterlichem Blut'], answer: 0, explain: 'NIPT hat PPV ~90% für Trisomie 21. Ist aber ein Screening-Test! Vor jeder irreversiblen Entscheidung: invasive Diagnostik (Amnio/CVS) zur Bestätigung.' },
  { q: 'Bei einem Kind mit V.a. Down-Syndrom zeigt FISH 3 Signale für Chromosom 21. Warum reicht FISH ALLEIN nicht aus?', choices: ['FISH unterscheidet nicht zwischen freier Trisomie und Translokation — für Wiederholungsrisiko ist der Mechanismus entscheidend', 'FISH ist unzuverlässig', 'FISH zeigt keine Mosaike', 'FISH ist veraltet'], answer: 0, explain: 'FISH zeigt nur Kopienanzahl, nicht den Mechanismus. Translokations-Down (~4%): Wiederholungsrisiko bis 100% bei rob(21;21)! Daher: IMMER vollständiger Karyotyp.' },
  { q: 'Welches maligne Erkrankungsrisiko ist bei Kindern mit Down-Syndrom am stärksten erhöht?', choices: ['Akute megakaryoblastische Leukämie (AMKL/AML M7) — 500× erhöht', 'Retinoblastom', 'Neuroblastom', 'Wilms-Tumor'], answer: 0, explain: 'AMKL: 500× erhöht bei Down. Auch ALL ~20× erhöht. Dagegen: solide Tumoren sind bei Down SELTENER (Tumorsuppressor-Effekt durch Trisomie 21?).' },
  { q: 'Eine 42-jährige Schwangere fragt nach dem altersabhängigen Risiko für Trisomie 21 bei Geburt. Korrekte Angabe?', choices: ['~1:35-40', '~1:100', '~1:350', '~1:700'], answer: 0, explain: 'Mit 42: ~1:35-40 bei Geburt. Mit 35: ~1:350. Mit 25: ~1:1250. Die Risikokurve steigt nach 35 exponentiell.' }
],

// ── Fall 2: Trisomie 18 ──────────────────────────────────────────
2: [
  { q: 'Welche Konstellation im Ersttrimesterscreening ist typisch für Trisomie 18?', choices: ['NT erhöht, freies beta-hCG erniedrigt, PAPP-A erniedrigt', 'NT normal, beta-hCG erhöht, PAPP-A erhöht', 'NT erhöht, beta-hCG erhöht, PAPP-A normal', 'Alles normal'], answer: 0, explain: 'Trisomie 18: BEIDE Marker erniedrigt (beta-hCG + PAPP-A) + NT erhöht. Trisomie 21: beta-hCG erhöht, PAPP-A erniedrigt. Wichtiger Unterschied!' },
  { q: 'Ein Paar hat ein Kind mit Trisomie 18 bekommen. In der nächsten Schwangerschaft zeigt der NIPT "low risk" für alle Trisomien. Welche Beratung ist korrekt?', choices: ['NIPT für Trisomie 18 hat niedrigeren PPV als für T21 — falsch-negative sind möglich, Sono-Kontrolle weiterhin wichtig', 'NIPT ist 100% sicher, keine weitere Diagnostik nötig', 'Nur relevant wenn Mutter >35 Jahre', 'NIPT erkennt nur Trisomie 21'], answer: 0, explain: 'NIPT-Sensitivität für T18 ~97% (vs. ~99% für T21). PPV abhängig von Prävalenz. Falsch-negativ bei confined placental mosaicism möglich.' },
  { q: 'Welcher Ultraschallbefund im 2. Trimenon ist am spezifischsten für Trisomie 18?', choices: ['Strawberry-shaped head (erdbeerförmiger Schädel) + Plexus-choroideus-Zysten + überkreuzte Finger', 'Nur Wachstumsretardierung', 'Megacisterna magna allein', 'Erhöhte Nackentransparenz allein'], answer: 0, explain: 'Erdbeer-Schädel (prominentes Okziput), Plexus-choroideus-Zysten (~50%), überkreuzte Finger, Omphalozele, singuläre Nabelarterie = Ultraschall-Kombination hochspezifisch.' },
  { q: 'Welche ethische Besonderheit gilt für Trisomie 18 im Vergleich zu Trisomie 21?', choices: ['Letale Prognose verändert die Beratungssituation — palliativer Ansatz vs. lebenslange Betreuung', 'Kein Unterschied in der Beratung', 'Trisomie 18 ist therapierbar', 'Trisomie 18 hat bessere Prognose'], answer: 0, explain: 'T18: >90% sterben im 1. Jahr. T21: Lebenserwartung >60 Jahre. Perinatalpalliatives Konzept vs. Therapieplanung — fundamental andere Beratungssituation.' },
  { q: 'Mosaik-Trisomie 18 wird auf der Amniozentese diagnostiziert. Confined Placental Mosaicism (CPM) muss ausgeschlossen werden. Warum?', choices: ['CVS zeigt den Trophoblasten-Karyotyp, nicht den fetalen — CPM kann falsch-positiv sein; Amnio gilt als zuverlässiger', 'CPM gibt es bei Trisomie 18 nicht', 'Amnio ist unzuverlässiger als CVS', 'Mosaik ist immer im Fetus'], answer: 0, explain: 'Bei CVS: Trisomie kann auf die Plazenta beschränkt sein (CPM Typ III). Amnio reflektiert den Fetus besser. Bei Mosaik-Befund: Kordozentese als Goldstandard erwägen.' }
],

// ── Fall 6: Turner 45,X ──────────────────────────────────────────
6: [
  { q: 'Eine Turner-Patientin plant eine Schwangerschaft mit Eizellspende. Welche Voruntersuchung ist ABSOLUT OBLIGAT?', choices: ['Kardio-MRT mit Aortenwurzel-Index (Aortendissektion-Risiko in SS!)', 'Nur gynäkologische Untersuchung', 'Kein besonderes Screening nötig', 'Nur Blutdruck-Messung'], answer: 0, explain: 'Aortenwurzel-Index (ASI) >25mm/m² KOF = KONTRAINDIKATION für Schwangerschaft! Turner-Patientinnen haben 2% Aortendissektionsrisiko in der SS (vs. 0.0003% normal).' },
  { q: 'Welche Aussage zu Wachstumshormon bei Turner ist KORREKT?', choices: ['Beginne so früh wie möglich — jedes Jahr Verzögerung kostet ~1cm Endgröße', 'Erst ab Pubertätsalter beginnen', 'Nur bei GH-Mangel im Stimulationstest', 'Wachstumshormon ist bei Turner kontraindiziert'], answer: 0, explain: 'GH bei Turner: KEINE GH-Defizienz nötig (SHOX-Haploinsuffizienz ist der Mechanismus). Früher Beginn (ab 4-6 Jahre) = besserer Endgrößen-Gewinn (~5-8 cm).' },
  { q: 'Bei einer 16-jährigen Turner-Patientin wird ein kryptisches Y-Fragment (SRY+) auf Microarray detektiert. Welche Konsequenz?', choices: ['Prophylaktische Gonadektomie wegen 15-30% Gonadoblastom-Risiko', 'Nur beobachten', 'Testosteron-Therapie', 'Hormonelle Stimulation der Gonaden'], answer: 0, explain: 'Y-Material + Gonadendysgenesie → Gonadoblastom-Risiko 15-30%. Prophylaktische Gonadektomie ist Standard. Vor OP: MRT zum Gonadennachweis.' },
  { q: 'Welches Antibiotikum erfordert bei Turner-Patientinnen besondere Vorsicht?', choices: ['Fluorchinolone (Aortenaneurysma-/Dissektionsrisiko bei vorbestehender Aortopathie)', 'Penicillin', 'Cephalosporine', 'Makrolide'], answer: 0, explain: 'FDA Black Box Warning: Fluorchinolone erhöhen Aortenruptur-Risiko. Bei Turner mit bereits erhöhtem Aorten-Risiko: doppelte Gefährdung. Vermeiden wenn möglich.' },
  { q: 'Welche endokrinologische Langzeitkomplikation bei Turner wird am häufigsten übersehen?', choices: ['Hashimoto-Thyreoiditis (~30%, jährliches TSH-Screening)', 'Diabetes Typ 1', 'Morbus Addison', 'Hyperthyreose'], answer: 0, explain: 'Hashimoto: ~30% der Turner. Oft subklinisch. Jährliche TSH/fT4/TPO-AK-Kontrolle lebenslang. Auch Zöliakie gehäuft (~5%), jährliches Screening empfohlen.' }
],

// ── Fall 7: Klinefelter 47,XXY ───────────────────────────────────
7: [
  { q: 'Welche Aussage zum Brustkrebs-Risiko bei Klinefelter ist KORREKT?', choices: ['20-50× erhöhtes Risiko (vergleichbar mit Frauen), Screening ab 50 empfohlen', 'Kein erhöhtes Risiko', 'Nur bei Gynäkomastie', '2× erhöhtes Risiko (klinisch irrelevant)'], answer: 0, explain: 'Klinefelter-Männer: Brustkrebsrisiko wie bei Frauen (Östrogeneffekt). Mammographie-Screening ab 50 diskutiert, Selbstuntersuchung empfohlen.' },
  { q: 'TESE bei Klinefelter: zu welchem Zeitpunkt hat die Spermiengewinnung die höchste Erfolgsrate?', choices: ['Möglichst früh — Spermatogenese deterioriert mit dem Alter; vor 35 optimal', 'Nach langer Testosteron-Therapie', 'Immer gleich', 'Erst nach 40'], answer: 0, explain: 'TESE-Erfolgsrate ~40-60% bei <35 Jahre, sinkt danach. CAVE: Exogenes Testosteron UNTERDRÜCKT residuelle Spermatogenese! Vor TESE: Testosteron absetzen + hCG/FSH.' },
  { q: 'Welche Aussage zu Testosteron-Substitution bei Klinefelter ist FALSCH?', choices: ['Testosteron erhöht die Spermienzahl', 'Testosteron verbessert Knochendichte', 'Testosteron reduziert viszerales Fett', 'Testosteron verbessert Libido und Energie'], answer: 0, explain: 'FALSCH: Exogenes Testosteron UNTERDRÜCKT die Spermatogenese über negative Rückkopplung (GnRH↓ → FSH/LH↓). Fertilität und Testosteron-Substitution sind gegensätzliche Ziele!' },
  { q: 'Ein 35-jähriger mit neu diagnostiziertem Klinefelter fragt nach dem Risiko für seine Kinder. Korrekte Beratung?', choices: ['Bei erfolgreicher TESE/ICSI: Nachkommen haben KEIN erhöhtes Klinefelter-Risiko', 'Alle Söhne werden XXY sein', '50% der Kinder betroffen', '25% Risiko'], answer: 0, explain: 'ICSI mit Klinefelter-Spermien: kein signifikant erhöhtes Aneuploidie-Risiko bei Nachkommen. PGT-A optional, aber nicht routinemäßig empfohlen.' },
  { q: 'Welche metabolische Komplikation bei unbehandeltem Klinefelter hat die höchste Mortalitätsrelevanz?', choices: ['Metabolisches Syndrom → KHK + Diabetes Typ 2 (Haupttodesursache)', 'Osteoporose-Frakturen', 'Leberversagen', 'Niereninsuffizienz'], answer: 0, explain: 'Kardiovaskuläre Mortalität ist die Haupttodesursache bei Klinefelter. Metabolisches Syndrom + Diabetes + Dyslipidämie. Testosteron-Substitution reduziert das Risiko.' }
],

// ── Fall 11: rob(13;14) ──────────────────────────────────────────
11: [
  { q: 'Eine Trägerin von rob(13;14) hat 3 Aborte gehabt. Karyotyp der POC zeigt 2× Monosomie 14, 1× Trisomie 14. Welche Schlussfolgerung?', choices: ['Adjacent-Segregation dominiert — die theoretisch mögliche Trisomie 13 wurde nicht gesehen, weil sie seltener lebensfähig den frühen Abort überlebt', 'Die Robertsonsche verursacht keine Aborte', 'Falsche Karyotypisierung', 'Zufall'], answer: 0, explain: 'Monosomie 13/14 und Trisomie 14 sind ALLE letal im 1. Trimenon. Trisomie 13 kann bis zur Geburt überleben (~1% empirisch). Die Abortkaryotypen bestätigen die unbalancierte Segregation.' },
  { q: 'PGT-SR wird angeboten. Wie viele Embryonen sind typischerweise transferierbar (normal oder balanciert)?', choices: ['~1/3 bis 1/2 (theoretisch 2/6 Segregationstypen sind normal/balanciert)', 'Alle Embryonen', 'Nur 1/6', '<10%'], answer: 0, explain: 'Alternate Segregation (normal + balanciert) = 2/6 theoretisch. Empirisch: ~30-50% der Embryonen sind transferierbar. Manche Studien zeigen höhere Raten.' },
  { q: 'Kann man im PGT-SR unterscheiden ob der Embryo normal (46,XX) oder Träger der Rob ist (45,XX,rob(13;14))?', choices: ['Nein — SNP-Array-basiertes PGT-SR kann balanciert nicht von normal unterscheiden', 'Ja, immer', 'Ja, mit WES', 'Nicht relevant'], answer: 0, explain: 'Array-basiertes PGT-SR misst Kopienzahl: normal und balanciert haben identische Kopienzahl für 13q und 14q. Unterscheidung nur durch Karyotyp des Kindes postnatal.' },
  { q: 'Was ist der Unterschied im empirischen Trisomie-13-Risiko zwischen männlichem und weiblichem rob(13;14)-Träger?', choices: ['Männlich: <1%; Weiblich: ~1% (Geschlechtsunterschied durch differentielle Gameten-Selektion)', 'Identisch bei beiden', 'Männlich höher', '10% bei beiden'], answer: 0, explain: 'Geschlechtsspezifischer Unterschied: Oogenese-Selektion anders als Spermatogenese. Empirisch: Mutter ~1%, Vater <1%. Gilt ähnlich für alle Robertsonschen.' },
  { q: 'Eine Patientin mit rob(13;14) und habituellen Aborten möchte wissen: ist eine natürliche Schwangerschaft mit PND eine Alternative zu PGT-SR?', choices: ['Ja — natürliche Konzeption + CVS/Amnio ist gleichwertige Option; PGT-SR vermeidet nur die emotionale Belastung eines Aborts nach PND', 'Nein, nur PGT-SR möglich', 'PND ist veraltet', 'Natürliche Konzeption ist kontraindiziert'], answer: 0, explain: 'Beide Wege evidenzbasiert: PGT-SR vermeidet unbalancierte Schwangerschaften, PND detektiert sie. Kumulative Schwangerschaftsrate pro Zyklus höher bei natürlicher Konzeption.' }
],

// ── Fall 16: Cri-du-chat ─────────────────────────────────────────
16: [
  { q: 'Bei einem Kind mit V.a. Cri-du-chat zeigt der Standard-Karyotyp einen normalen Befund. Nächster Schritt?', choices: ['Array-CGH — kleine 5p-Deletionen unter der Karyotyp-Auflösung (~5-10 Mb) sind häufig', 'Diagnose verwerfen', 'FISH für Trisomie 21', 'Karyotyp wiederholen'], answer: 0, explain: 'Karyotyp-Auflösung: ~5-10 Mb. Kleine terminale 5p-Deletionen können submikroskopisch sein. Array-CGH erkennt sie zuverlässig bis <100 kb.' },
  { q: 'Die Elternkaryotypen zeigen bei der Mutter eine balancierte Translokation t(5;8). Konsequenz?', choices: ['15% der Cri-du-chat-Fälle: parentale Translokation → hohes Wiederholungsrisiko → PND/PGT für alle weiteren SS', 'Keine Relevanz', 'Nur für die Mutter relevant', 'Wiederholungsrisiko ist 0%'], answer: 0, explain: '~15% von Cri-du-chat sind aus parentaler Translokation. Wiederholungsrisiko bei balancierten Trägern: ~10-15%! Kaskadenscreening der Familie.' },
  { q: 'Welche Genotyp-Phänotyp-Korrelation ist bei 5p-Deletion etabliert?', choices: ['Schrei-Region (5p15.3, CTNND2) und ID-Region (5p15.2) sind separate kritische Regionen', 'Deletionsgröße korreliert nicht mit Schwere', 'Nur ein Gen verantwortlich', 'Keine Korrelation möglich'], answer: 0, explain: 'Kritische Region Schrei: 5p15.3 (CTNND2, FLJ25076). Kritische Region ID: 5p15.2 (SEMA5A, TERT). Kleine Deletionen können Schrei OHNE schwere ID haben.' },
  { q: 'Welche Aussage zur Prognose bei Cri-du-chat ist KORREKT?', choices: ['Überlebensrate >85% bis Erwachsenenalter, schwere ID aber keine schwere Organpathologie', 'Immer letal im Kindesalter', 'Normale Lebenserwartung und Intelligenz', 'Nur wenige Monate'], answer: 0, explain: 'Keine lebensbedrohliche Organbeteiligung (anders als T13/T18). Hauptproblem: schwere ID, Verhaltensprobleme. Mit guter Betreuung: Erwachsenenalter erreichbar.' },
  { q: 'Welcher der folgenden Tests wäre für die Erstdiagnostik bei V.a. Mikrodeletionssyndrom aktuell am besten geeignet?', choices: ['Chromosomaler Microarray (Array-CGH/SNP-Array) als Erstlinien-Diagnostik', 'Karyotyp allein', 'WES als Erstlinie', 'Nur klinische Diagnose'], answer: 0, explain: 'Array-CGH ist seit 2010 empfohlene Erstlinien-Diagnostik bei Entwicklungsverzögerung + Dysmorphie (ACMG/AAP). Diagnostische Ausbeute ~15-20% (vs. ~3% Karyotyp).' }
],

// ── Fall 17: DiGeorge 22q11.2 ────────────────────────────────────
17: [
  { q: 'Bei einem Kind mit 22q11.2-Deletion wird eine Lebendimpfung geplant. Welche Diagnostik ist VORHER obligat?', choices: ['T-Zell-Subpopulationen (CD3/CD4/CD8) — bei schwerer T-Zell-Depletion sind Lebendimpfungen kontraindiziert', 'Nur Blutbild', 'Keine Voruntersuchung', 'IgG-Spiegel allein reicht'], answer: 0, explain: 'DiGeorge-Immundefekt: Thymusaplasie/-hypoplasie → T-Zell-Mangel. Bei <200/µl CD4+ T-Zellen: KEINE Lebendimpfungen (BCG, MMR, Varizellen)! Vorher immer Immunstatus.' },
  { q: 'Welche Hypokalzämie-Ursache bei 22q11.2-Deletion ist am gefährlichsten und wird am häufigsten initial verpasst?', choices: ['Neonatale Hypokalzämie durch Parathormon-Insuffizienz — oft erst durch Krampfanfälle auffällig', 'Vitamin-D-Mangel', 'Alimentäre Ursache', 'Medikamenten-Nebenwirkung'], answer: 0, explain: 'PTH-Mangel durch Nebenschilddrüsen-Hypoplasie: neonatal oft asymptomatisch, dann plötzlich Krampfanfälle. JEDES Neugeborene mit Herzfehler: Calcium + PTH messen!' },
  { q: 'Die 22q11.2-Deletion wird durch NAHR vermittelt. Warum ist die Deletion so häufig (~1:4000)?', choices: ['8 LCR22-Blöcke (Low Copy Repeats) prädisponieren für Fehlpaarung in Meiose → höchste Rekurrenzrate aller NAHR-Syndrome', 'Hohe Mutationsrate von TBX1', 'Founder-Effekt', 'Umweltfaktoren'], answer: 0, explain: 'Die 22q11.2-Region hat 8 LCR22-Blöcke mit >96% Sequenzhomologie. Das macht sie zur "Hot-Spot"-Region für NAHR — häufiger als jede andere Mikrodeletion.' },
  { q: 'Welche Aussage zur Vererbung bei 22q11.2-Deletion ist für die Beratung am wichtigsten?', choices: ['10% der Fälle sind von einem (oft mild betroffenen!) Elternteil ererbt — IMMER Eltern testen', 'Immer de novo', 'Autosomal rezessiv', 'X-chromosomal'], answer: 0, explain: '~10% ererbt, oft vom milde betroffenen Elternteil (variable Expressivität!). Der Elternteil kann z.B. nur VPI oder Lernstörung haben. Eltern-FISH/Array IMMER.' },
  { q: 'Welche operative Besonderheit muss VOR einer velopharyngealen Chirurgie bei 22q11.2 beachtet werden?', choices: ['Medialisierte/aberrante A. carotis interna bei ~25% — MR-Angiographie obligat vor OP', 'Keine Besonderheit', 'Nur Blutungsrisiko', 'Laryngoskopie reicht'], answer: 0, explain: 'Aberrante Carotiden: bei ~25% der 22q11.2-Patienten medialisiert, liegen hinter dem Pharynx. OP ohne MRA → Carotis-Verletzung → katastrophale Blutung/Schlaganfall.' }
],

// ── Fall 18: Prader-Willi ────────────────────────────────────────
18: [
  { q: 'Ein Kind mit klinischem V.a. PWS: Methylierungstest zeigt paternales Methylierungsmuster. Diagnose bestätigt. Welcher nächste Test differenziert den Mechanismus?', choices: ['FISH/Array (Deletion?) → falls negativ: UPD-Test (maternale UPD15?) → falls negativ: Imprinting-Center-Analyse', 'Kein weiterer Test nötig', 'WES', 'Nur klinische Klassifikation'], answer: 0, explain: 'Stufendiagnostik: 1. Methylierungstest (Screening, erkennt alle Formen). 2. FISH/Array (Deletion ~70%). 3. UPD-Mikrosatelliten (~25%). 4. IC-Analyse (2-5%). Mechanismus bestimmt Wiederholungsrisiko!' },
  { q: 'Warum ist das Wiederholungsrisiko bei IC-Deletion (Imprinting-Center) DRAMATISCH anders als bei de-novo-Deletion?', choices: ['IC-Deletion kann bis zu 50% Wiederholungsrisiko haben (abhängig ob Vater die IC-Deletion trägt)', 'Immer gleich niedrig', 'IC-Deletion ist immer de novo', 'Kein Unterschied'], answer: 0, explain: 'IC-Deletion im Vater: 50% Risiko für PWS bei jedem Kind (IC-Deletion → paternales Allel kann nicht paternal geprägt werden). De-novo-Deletion: <1%.' },
  { q: 'Welche Todesursache ist bei PWS-Erwachsenen am häufigsten und potenziell vermeidbar?', choices: ['Erstickung (Aspiration wegen Hyperphagie + reduziertem Würgereflex)', 'Herzinfarkt', 'Sepsis', 'Suizid'], answer: 0, explain: 'Haupttodesursache: Aspiration/Erstickung (Hyperphagie → Binge-Eating → Aspiration). Respiratorische Insuffizienz (Adipositas + zentrale Hypoventilation) auf Platz 2.' },
  { q: 'Wachstumshormon bei PWS: welche Vorsichtsmaßnahme ist VOR Therapiebeginn obligat?', choices: ['Polysomnographie — obstruktive Schlafapnoe bei PWS häufig, GH kann Adenoid-Hypertrophie verschlimmern', 'Keine Voruntersuchung', 'Nur Blutbild', 'IGF-1-Messung allein'], answer: 0, explain: 'GH bei PWS verbessert Körperzusammensetzung und Wachstum, ABER: Risiko der Verschlechterung von Schlafapnoe (Adenoid-Hypertrophie). Polysomnographie vor und 6 Wochen nach Start.' },
  { q: 'Welche Aussage zur maternalen UPD15 (mat UPD15) als PWS-Ursache ist KORREKT?', choices: ['Entsteht meist durch Trisomie-Rescue: trisome Zygote (47,+15) verliert 1 Chromosom 15 → 1/3 Chance auf mat UPD', 'Entsteht durch Deletion', 'Immer familiär', 'Durch Translokation bedingt'], answer: 0, explain: 'Trisomie 15 → Rescue (Verlust eines Chr15) → 1/3 Chance dass das paternale verloren geht → mat UPD15 → PWS. Wiederholungsrisiko: sehr gering.' }
],

// ── Fall 19: Angelman ────────────────────────────────────────────
19: [
  { q: 'Methylierungstest bei V.a. Angelman ist NORMAL. Kann die Diagnose trotzdem stimmen?', choices: ['Ja — ~10% haben UBE3A-Punktmutation, die der Methylierungstest NICHT erkennt', 'Nein, Angelman ausgeschlossen', 'Nur bei Mosaik', 'Methylierungstest ist unzuverlässig'], answer: 0, explain: 'Methylierungstest erkennt: Deletion, pat. UPD, IC-Defekt (~90%). Aber UBE3A-Punktmutationen (~10%) ändern die Methylierung NICHT. Bei normalem Test + klinischem V.a.: UBE3A-Sequenzierung!' },
  { q: 'Welches Antiepileptikum ist bei Angelman-Epilepsie KONTRAINDIZIERT?', choices: ['Carbamazepin und Lamotrigin (können Anfälle verschlimmern!)', 'Valproat', 'Levetiracetam', 'Clobazam'], answer: 0, explain: 'Carbamazepin + Lamotrigin: Na-Kanalblocker verschlechtern Angelman-Epilepsie! Mittel der Wahl: Valproat, Levetiracetam, Benzodiazepine (Clobazam).' },
  { q: 'Warum ist Angelman im Gegensatz zu PWS erst nach 12 Monaten klinisch sicher diagnostizierbar?', choices: ['Lachattacken, Ataxie und Epilepsie manifestieren sich erst im Laufe des 1. Lebensjahres; neonatal nur unspezifische Symptome', 'Methylierungstest erst ab 12 Monate zuverlässig', 'DNA erst postnatal stabil', 'Angelman existiert vor 12 Monaten nicht'], answer: 0, explain: 'Neugeborene mit Angelman: nur Trinkschwäche/Hypotonie (unspezifisch). Lachattacken ab 6-12 Mo., Ataxie beim Laufenlernen, Epilepsie >12 Mo. Daher: Diagnose oft erst mit 2-3 Jahren.' },
  { q: 'Welche Therapie ist für Angelman aktuell in klinischer Entwicklung am vielversprechendsten?', choices: ['Antisense-Oligonukleotide (ASO) zur Aktivierung des paternalen UBE3A-Allels (UBE3A-AS silencing)', 'Gentherapie mit AAV', 'Stammzelltransplantation', 'Enzymersatz'], answer: 0, explain: 'UBE3A-AS-Silencing: ASOs blockieren den antisense-Transkript von UBE3A auf dem paternalen Allel → De-Silencing → paternales UBE3A wird exprimiert. Phase 1/2-Studien laufen (GeneTx/Ultragenyx).' },
  { q: 'Warum ist die EEG-Auffälligkeit bei Angelman diagnostisch wertvoll?', choices: ['Pathognomonisches Muster (hochamplitudige 2-3 Hz Delta, posterior betont) kann bereits VOR Krampfanfällen die Diagnose lenken', 'EEG ist immer normal', 'Nur bei Anfällen auffällig', 'Unspezifisch'], answer: 0, explain: 'Angelman-EEG: charakteristisch schon im 1. Lebensjahr (vor Anfällen!). Rhythmische hochamplitudige 2-3 Hz delta, trihasische Wellen posterior. Kein anderes Syndrom zeigt dieses Muster so früh.' }
],

};

// Attach expert questions to QUIZ_CASES
if (typeof window !== 'undefined') {
  window.QUIZ_EXPERT = QUIZ_EXPERT;
}
